  
version: 2

references:
  default_docker_ruby_executor: &default_docker_ruby_executor
    image: circleci/ruby:2.7.0
    environment:
      BUNDLE_JOBS: 3
      BUNDLE_RETRY: 3
      BUNDLE_PATH: vendor/bundle
      PGHOST: 127.0.0.1
      PGUSER: postgres
      PGPASSWORD: ""
      RAILS_ENV: test
  postgres: &postgres
    image: circleci/postgres:9.6-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: tailorshop_api_test
      POSTGRES_PASSWORD: ""

jobs:
  build:
    docker:
      - *default_docker_ruby_executor
    steps:
      - checkout
      # Which version of bundler?
      - run:
          name: Which bundler?
          command: bundle -v
      # bundle cache
      - restore_cache:
          keys:
            - tailorshop-api-bundle-v2-{{ checksum "Gemfile.lock" }}
            - tailorshop-api-bundle-v2-
      - run:
          name: Bundle Install
          command: bundle check || bundle install
      # Store bundle cache
      - save_cache:
          key: tailorshop-api-bundle-v2-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
  test:
    parallelism: 3
    docker:
      - *default_docker_ruby_executor
      - *postgres
    steps:
      - checkout
      - restore_cache:
          keys:
            - tailorshop-api-bundle-v2-{{ checksum "Gemfile.lock" }}
            - tailorshop-api-bundle-v2-
      - run:
          name: Bundle Install
          command: bundle check || bundle install
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Database setup
          command: bundle exec rails db:schema:load --trace
      - run:
          name: Install Code Climate Test Reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      # Run rspec in parallel
      - run:
          command: |
            mkdir /tmp/test-results
            mkdir -p test-results/rspec test-artifacts
            bundle exec rspec  --profile 10 --format progress
    
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
  
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
